# Generated by Django 2.0.3 on 2019-10-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_question_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
