# Generated by Django 2.0.3 on 2019-10-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191012_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('visual', models.IntegerField()),
                ('auditory', models.IntegerField()),
                ('kinect', models.IntegerField()),
            ],
        ),
    ]
